name: Publish To Website

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: "Build application"
        run: "npm run build"
        env:
          REACT_APP_CLIENT_ID: ${{ secrets.REACT_APP_CLIENT_ID }}
          PUBLIC_URL: ${{ secrets.PUBLIC_URL }}
      - name: "Deploy application"
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          folder: build
          token: ${{ secrets.PUBLISH_ACCESS_TOKEN }}
